use_frameworks!
platform :ios, '8.0'

target 'KFXUtilities_Example' do
  pod 'KFXUtilities', :path => '../'
  
  # Pods for Main target
  pod 'KFXCore'

  target 'KFXUtilities_Tests' do
    inherit! :search_paths
  end
end
